### ISSUE TITLE
Lock with leases

### ISSUE THREAD

**Issue by connor4312** [kragniz/python-etcd3#109]
I was browsing through this client while working on a version for Node.js. I noticed that your locking is implemented on a straight k/v without using a lease. I suggest you consider using a lease for this, so that if something happens to the server or application which makes the lock, the resource isn't abandoned indefinitely. The downside is that it's possible that a lock is 'lost' while a process thinks it has it, but the set of situations in which that can occur and cause issues is a strict subset of the situations (only one I can think of: a partial network partition) in which the lock would otherwise be held indefinitely.

My implementation and little more reasoning is here, if you're interested: https://github.com/WatchBeam/etcd3/pull/5

**Comment by kragniz** [comment]
The lock code is pretty dodgy, but it does use a lease https://github.com/kragniz/python-etcd3/blob/master/etcd3/locks.py#L57

It's mostly a stop-gap until https://github.com/coreos/etcd/pull/7444 is released, at which point I'll switch to using that.

**Comment by connor4312** [comment]
Ah, great. Somehow I skimmed over that. Nevermind then! 😄
