### ISSUE TITLE
Lock.acquire method misses DELETE event while waiting

### ISSUE THREAD

**Issue by cenkalti** [kragniz/python-etcd3#1107]
... because it does not pass revision number to `watch_once` method. If DELETE event happens before watch, it does not get sent to the watcher and `acquire` waits to end of timeout.

Go implementation does it correctly: https://github.com/etcd-io/etcd/blob/7eae024eade9e4d523544026c9312b687dbfae94/clientv3/concurrency/mutex.go#L85

The bug is introduced in this commit: https://github.com/kragniz/python-etcd3/commit/59c16eb4322835e7fc2fb1409071dd77e50f082a

It's interesting no one has reported this issue since 2017.

**Comment by kragniz** [comment]
Nice, could you send a PR?

**Comment by cenkalti** [comment]
Working on it...
