### ISSUE TITLE
Dockerfile python version

### ISSUE THREAD

**Issue by dimd** [kragniz/python-etcd3#115]
The python docker image version is not decalring a specific version, so the latest one is downloaded.
Currently the latest version is 3.6.1. This causes this step of the image build to fail:

```bash
RUN tox -epy35 --notest
``` 

since python3.5 is not installed.

One solution would be to explicitly declare the desired python version in the FROM directive.

**Comment by kragniz** [comment]
Yeah, depending on the `latest` tag is always a bad idea.

Do you fancy making a pull request to fix it?

**Comment by dimd** [comment]
Yeah sure! It's pretty straightforward.

**Comment by kragniz** [comment]
Fixed in #117
