### ISSUE TITLE
AttributeError on Watch Filters during Create Watch Request

### ISSUE THREAD

**Issue by MrManicotti** [kragniz/python-etcd3#1566]
## Issue Description
On adding a filter to a watch request, `Watcher._create_watch_request` will throw an AttributeError due to a direct `filters` assignment to a proto `repeated` object

## Error log
```
  File "/Users/example/Documents/example/example/test.py", line 32, in _create_watch_request
    create_watch.filters = filters
AttributeError: Assignment not allowed to repeated field "filters" in protocol message object.
```

## Resolution
`create_watch.filters.extend(filters)` instead of assignment

**Comment by kragniz** [comment]
Fixed in #1567
