### ISSUE TITLE
etcd3-client throwing error -

### ISSUE THREAD

**Issue by aru88** [kragniz/python-etcd3#2340]
Hello,

i have deployed my python service in kubernates cluster . both service and etcd is deployed in non tls mode  in istio-proxy service mesh.
now using etcd3 client i am trying to connect with the etcd but it's throwing me error while trying to get key from etcd. 

An error has occurred <_InactiveRpcError of RPC that terminated with:       status = StatusCode.INVALID_ARGUMENT    details = etcdserver: user name is empty        debug_error_string = UNKNOWN:Error received from peer  {grpc_message:etcdserver: user name is empty, grpc_status:3, created_time:2023-12-01T19:00:31.101268091+00:00} >

'etcd3==0.12.0', version i am using .

this is the code snippet 
in below code in read function on line     return con.get(key)  it's throwing error .

 def _create_connection(self):
        '''method to create the client to connect to etcd'''
        try:
            client = None
            logger.info("Generating ETCD client without certifcates")
            logger.info(f"ETCD host {CONFIG.get(CONFIG_ETCD_HOST)}")
            client = etcd3.client(
                    host=CONFIG.get(CONFIG_ETCD_HOST),
                    port=CONFIG.get(CONFIG_ETCD_PORT)
                )
            logger.info("CONN Created")
            logger.info(f"CONN {client}")
            if client:
                # Perform operations with the client
                # For example:
                logger.info(f"Connected to ETCD at {CONFIG.get(CONFIG_ETCD_HOST)}:{CONFIG.get(CONFIG_ETCD_PORT)}")  # noqa
            else:
                logger.warning("Client is not instantiated")
            return client
        except etcd3.Etcd3Exception as exe:
            logger.error("exception occuerd while establishing the connection", exe)  # noqa
            raise
        except Exception as exe:
            logger.error("generic exception thrown", exe)

def read(self, prefix, key):
        '''method to read data from etcd'''
        try:
            con = self._create_connection()
            logger.info("Read etcd conenction created ")
            key = prefix+key
            logger.debug("key: {}".format(key))
            return con.get(key)
        except etcd3.Etcd3Exception as exe:
            logger.error(
                "error while fetching value for a key", exe
            )
            raise
        except Exception as exe:
            logger.error(
                "generic exception while reading the value from etcd", exe
            )
            raise

**Comment by huizsh** [comment]
@aru88 how was this resolved? I had the same issue when using UserGet/UserChangePassword API
```
        request = etcd_messages.AuthUserChangePasswordRequest(
            name=username,
            password=new_password
        )
        print(request)
        getRequest = etcd_messages.AuthUserGetRequest(
            name=username
        )
        etcd_client = getETCDClient(username, old_password)
        # Send the request to etcd
        etcd_client.auth_stub.UserGet(getRequest)
        #etcd_client.auth_stub.UserChangePassword(request)
```
        status = StatusCode.INVALID_ARGUMENT
        details = "etcdserver: user name is empty"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:166.9.12.207:30144 {created_time:"2024-08-20T01:01:17.24349395+00:00", grpc_status:3, grpc_message:"etcdserver: user name is empty"}"
