### ISSUE TITLE
Bug: Can't kill the process of watch unless kill -9 in python27

### ISSUE THREAD

**Issue by xuhuigithub** [kragniz/python-etcd3#437]
HI @jd 
When I used watch code in Python 2.7, when I wanted to stop watch, I found that I could not stop it unless I forced it.

```python
import etcd3
etcd = etcd3.client(host='192.168.61.90', port=2379)
events_iterator, cancel = etcd.watch("/watch")

for event in events_iterator:
  print(event.value)
```

**Comment by xuhuigithub** [comment]
But I finally found the reason, because Python native queue library Queue.Queue, when using the get method of the queue instance, there will be a mutex blocking all threads. I did a test with the following code ,is it similar to your code?[https://github.com/kragniz/python-etcd3/blob/a3ccb115bdb2c2b9c2e4b590991dd50170dbc3ef/etcd3/client.py#L504](https://github.com/kragniz/python-etcd3/blob/a3ccb115bdb2c2b9c2e4b590991dd50170dbc3ef/etcd3/client.py#L504)
```bash
from Queue import Queue
q = Queue()
while True:
    q.get()
```
Yes, I can't kill him too unless I force it.

**Comment by jd** [comment]
AFAIU this is not a bug. It's just the way it's designed, it's a blocking iterator.

**Comment by xuhuigithub** [comment]
I'm sorry, I corrected my words, and logically he doesn't seem to want to be a bug, but in practice, this code blocks the main thread, which is a bug.

**Comment by jd** [comment]
It's not a bug. It's a design.
Just start another thread.

**Comment by xuhuigithub** [comment]
Well, maybe I'm not very clear about it. I said the blocking of the main thread is when I send the signal 15 to the program, the program does not respond normally.

**Comment by xuhuigithub** [comment]
This causes me to have kill -9 every time.

**Comment by jd** [comment]
```
$ python3 -c 'import queue; queue.Queue().get()'
```
in another tem:
```
kill -15 `pidof Python`
```
```zsh: terminated  python3 -c 'import queue; queue.Queue().get()'```

not sur what to say.

**Comment by xuhuigithub** [comment]
Ok, It's my fault.

**Comment by xuhuigithub** [comment]
Thank you very much,  @jd .
