### ISSUE TITLE
0.8.1 not on PyPI

### ISSUE THREAD

**Issue by jd** [kragniz/python-etcd3#442]
@kragniz I've pushed 0.8.1 tag but somehow it did not end up on PyPI. Not sure what I've missed?

**Comment by kragniz** [comment]
I took a look and it seems like the release automation is broken now, since it's still checking $TOXENV which was removed a while ago:

https://github.com/kragniz/python-etcd3/blob/master/.travis.yml#L33

**Comment by kragniz** [comment]
I need to spend some more time maintaining this :cry:

**Comment by jd** [comment]
@kragniz Can you upload manually in the meantime?

**Comment by kragniz** [comment]
pushed
