### ISSUE TITLE
Working add_watch_callback example (or what is the diff between watch)

### ISSUE THREAD

**Issue by ayashjorden** [kragniz/python-etcd3#594]
Hi all,
I'm not the python expert, but would like to make use `add_watch_callback`.

Current code  in the constructor:
```
        self.watch_id = self.client.add_watch_callback(
            prefix, callback=self.dequeue)
```

Thank you,
Jorden

**Comment by harshanarayana** [comment]
@ayashjorden If you look at the implementation details of  `add_watch` you notice that it internally makes use of `add_watch_callback` itself. However, the difference is that `watch` provides a blocking behavior wherein `add_watch_callback` provides a non-blocking behavior.

```python
import etcd3

client = etcd3.client()

def callback(event):
    print("From Callback : {}".format(event))

# watch events on foo, foo1
client.add_watch_callback("foo", callback, range_end="foo2")

print("Non Blocking")

counter = 0
events, cancel = client.watch("/somekey")
for event in events:
    print("From Iterator: {}".format(event))
    counter += 1
    if counter == 3:
        cancel()

print("Blocking")
```

Run the above code in one terminal and perform the `etcdctl` operation from another terminal on keys `/somekey` and `foo`/`foo1` to see the behavior.

Hope this answers your question.

**Comment by ayashjorden** [comment]
Yep, thank you!
