### ISSUE TITLE
Adding a callback to watch a prefix

### ISSUE THREAD

**Issue by yannlambret** [kragniz/python-etcd3#71]
Hi,

It looks like there is currently no way to add a callback to watch a prefix. Client's `add_watch_callback` method works perfectly when watching a key, but the only way to watch a prefix is to do it in a blocking way as shown in the README:

```python
watch_count = 0
events_iterator, cancel = etcd.watch_prefix("/doot/watch/prefix/")
for event in events_iterator:
    print(event)
    watch_count += 1
    if watch_count > 10:
        cancel()
```
When doing this in a dedicated thread, the execution is blocked as long as the `events_iterator` generator does not yield any value, and I'm not able to interrupt the thread. Am I missing something,  or should there be an `add_watch_prefix_callback` dedicated method?

**Comment by yannlambret** [comment]
To answer my own question, I managed to do it by using the `range_end` kwarg of the `add_watch_callback` method.

**Comment by daoiqi** [comment]
It is to expose too implementation details to use param `range_end` for user?
