### ISSUE TITLE
Misleading doc

### ISSUE THREAD

**Issue by miha-plesko** [kragniz/python-etcd3#719]
Hi, thanks for this awesome project. Wanted to let you know in current docs you say

```python
# locks
lock = etcd.lock('thing')
# do something
lock.release()
```

which is not working, because lock has to be acquired!

```python
# locks
lock = etcd.lock('thing')
lock.acquire()  # <------------------------- this is missing
# do something
lock.release()
```

**Comment by kragniz** [comment]
@miha-plesko want to send a patch?

**Comment by miha-plesko** [comment]
Thanks @kragniz and sorry that I forgot to respond
