### ISSUE TITLE
Pip install from git fails

### ISSUE THREAD

**Issue by niconorsk** [kragniz/python-etcd3#866]
`pip install git+https://github.com/kragniz/python-etcd3
Collecting git+https://github.com/kragniz/python-etcd3
  Cloning https://github.com/kragniz/python-etcd3 to /tmp/pip-req-build-h_7qgp3d
  Running command git clone -q https://github.com/kragniz/python-etcd3 /tmp/pip-req-build-h_7qgp3d
    ERROR: Command errored out with exit status 1:
     command: /home/nicolai.moore/src/product/slsecure/.tox/integration/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h_7qgp3d/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h_7qgp3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-h_7qgp3d/
    Complete output (1 lines):
    error in etcd3 setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-r base.'"
`
Tested with pip3.6 19.2.3 and pip3.6 10.0
This seems to have been introduced by https://github.com/kragniz/python-etcd3/pull/854

**Comment by kragniz** [comment]
Cheers.

@funkyHat mind taking a look?

**Comment by funkyHat** [comment]
yep that was me, sorry!
