### ISSUE TITLE
Watch with no etcd up - Infinite loop

### ISSUE THREAD

**Issue by ChristopheDaSilva** [kragniz/python-etcd3#88]
Hi, 

When we try, to add a watch but etcd is not running, there is no exception raise or status failed return.

In the next example, I try to connect the with the wrong port. No issue for client creation, but when I create my watch, etcd3 never return.

```
>>> import etcd3
>>> c=etcd3.client(host='127.0.0.1', port='2378', timeout=3)
>>> c.watch_once('1111')
```

In the watch.py file (add_callback method), the watch queue is not receiving the watcher timeout.

I think at this line:
`return self._watch_id_queue.get()`
should send the timeout value:
`return self._watch_id_queue.get(timeout=self.timeout)`

In this case, the add_callback can catch the Empty exception sent by queue.Queue.

Best regards,

**Comment by kragniz** [comment]
That sounds like a reasonable change. Do you fancy making a pull request for it?

**Comment by ChristopheDaSilva** [comment]
Yes, I will make it.

**Comment by kragniz** [comment]
Great, thanks!

**Comment by kragniz** [comment]
Hey @ChristopheDaSilva, any update on this? Need any help?

**Comment by gkarvounis** [comment]
Similar problem exists when etcd terminates after watch has been initiated.
For example, while following script is running, etcd shutdown does not cause any exception:
```import etcd3
c = etcd3.client("127.0.0.1")
print c.get("foo")

stream, cancel = c.watch("foo")
for evt in stream:
    print evt
```
Would the patch mentioned above fix this issue as well?

**Comment by nmakro** [comment]
Hi,

It seems that any call to a client that is not initialized properly never returns.

etcd_con = etcd3.client(host='wrong_host', port=1234)
etcd_con.status()

It hangs and i have to Ctrl-C to stop it.
Traceback:
python test_etcd.py 
^CTraceback (most recent call last):
  File "test_etcd.py", line 6, in <module>
    etcd_con.status()
  File "/usr/lib/python2.7/site-packages/etcd3/client.py", line 31, in handler
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/etcd3/client.py", line 334, in status
    status_response = self.maintenancestub.Status(status_request)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 506, in __call__
    credentials)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 500, in _blocking
    _handle_event(completion_queue.poll(), state,
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 114, in grpc._cython.cygrpc.CompletionQueue.poll (src/python/grpcio/grpc/_cython/cygrpc.c:10475)
KeyboardInterrupt

You can test it with any other method like put(), get(), lease() etc..
